config/routes.rb
C4::Application.routes.draw do
  devise_for :users

  resource  :home, only: [:index]
  resources :achievements, only: [:show, :new, :create, :index]
  resources :users, only: [:show]
  resource  :votes, only: [:create]
  resource  :subscriptions, only: [:create]

  authenticated :user do
    root :to => 'achievements#index'
  end
  root :to => 'home#index'
end

app/models/achievement.rb
# == Schema Information
#
# Table name: achievements
#
#  id                 :integer          not null, primary key
#  title              :string(255)      not null
#  description        :text             not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  badge_file_name    :string(255)
#  badge_content_type :string(255)
#  badge_file_size    :integer
#  badge_updated_at   :datetime
#

class Achievement < ActiveRecord::Base
  attr_accessible :title, :description

  has_attached_file :badge
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  achievement_id :integer
#  succeeded      :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :achievement
  has_many :votes

  scope :succeeded, where(succeeded: true)
  scope :not_succeeded, where(succeeded: false)

  attr_accessible :user_id, :achievement_id

  validates_uniqueness_of :user_id, scope: :achievement_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  prenom                 :string(255)
#  nom                    :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :achievements, through: :subscriptions
  has_many :subscriptions
  has_many :voted_subscriptions, through: :votes
  has_many :votes
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  subscription_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Vote < ActiveRecord::Base
  attr_accessible :user_id, :subscription_id
  belongs_to :user
  belongs_to :subscription

  validates_presence_of :user
  validates_presence_of :subscription
  validates_uniqueness_of :user_id, scope: :subscription_id

  after_save :validate_objective!

  VOTES_NUMBER = 10

  def validate_objective!
    if subscription.votes.count == VOTES_NUMBER then
      subscription.succeeded = true
      subscription.save
    end
  end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(params[:achievement])
    @achievement.save
    redirect_to new_achievement_path
  end

  def index
    @achievements = Achievement.all
  end

  def show
    @achievement = Achievement.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/subscriptions_controller.rb
#encoding: UTF-8
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  def create
    @subscription = Subscription.create( { user_id: current_user.id, achievement_id: params[:subscription][:achievement_id] } )
    unless @subscription.new_record? then
      flash[:notice] = 'Vous vous êtes bien abonné à cet objectif'
    end
    redirect_to achievements_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @succeeded_subscriptions = User.find(params[:id]).subscriptions.succeeded
    @not_succeeded_subscriptions = User.find(params[:id]).subscriptions.not_succeeded
  end
end

app/controllers/votes_controller.rb
#encoding: UTF-8
class VotesController < ApplicationController
  def create
    subscription = Subscription.find(params[:vote][:subscription_id])
    @vote = Vote.create( { user_id: params[:vote][:user_id], subscription_id: params[:vote][:subscription_id] } )
    unless @vote.new_record? then
      flash[:notice] = 'Votre vote a bien été enregistré'
    end
    redirect_to subscription.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/achievements/index.html.haml
%h1 Index Achievement
- if @achievements.any?
  %ul
    - @achievements.each do |achievement|
      %li
        = achievement.id
        = link_to achievement.title, achievement
        = achievement.description
        - if user_signed_in? && !current_user.achievements.include?(achievement)
          %br
          = link_to "Ajouter à mes objectifs", subscriptions_path( { subscription: { achievement_id: achievement.id} } ), method: :post
      %br

app/views/achievements/new.html.haml
%h1 New Achievement
= form_for @achievement do |f|
  #title
    = f.label :title
    = f.text_field :title, required: true
  #description
    = f.label :description
    = f.text_area :description, required: true, cols: 3, rows: 5
  = f.submit 'Envoyer', class: 'btn btn-primary'

app/views/achievements/show.html.haml
%h1 Show Achievement
%ul
  %li= "id : " << @achievement.id.to_s
  %li= @achievement.title
  %li= "description : " << @achievement.description
  %li= image_tag @achievement.badge.url unless @achievement.badge_file_name.nil?

app/views/home/index.html.haml
%h1 Welcome on C4 !
= render 'users/registrations/new'

app/views/layouts/_navigation.html.haml
%a.btn.btn-navbar{'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

-# Be sure to leave the brand out there if you want it shown
= link_to 'Le Projet Agile', root_path, :class => 'brand'

-# Everything you want hidden at 940px or less, place within here
.nav-collapse.collapse
  %ul.nav
    %li= link_to 'Liste des objectifs', achievements_path
    %li= link_to 'Proposer un nouvel objectif', new_achievement_path
    %li= link_to 'Voir mon profil public', current_user if user_signed_in?
  %ul.nav
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Account
        %b.caret
      %ul.dropdown-menu
        %li
        - if user_signed_in?
          %li= link_to('Editer mon compte', edit_user_registration_path)
          %li= link_to('Déconnexion', destroy_user_session_path, :method => :delete)
        - else
          %li= link_to('Connexion', new_user_session_path)
          %li= link_to('Inscription', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title Le Projet Agile
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container-fluider
      .row-fluid
        .span12
          .navbar.navbar-fixed-top
            .navbar-inner
              .container
                = render 'layouts/navigation'
      .row-fluid
        .span1
        .span10
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                %a.close{"data-dismiss" => "alert"} ×
                = content_tag :div, msg, :id => "flash_#{name}"
          = yield
        .span1

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
- if user_signed_in? && current_user == @user
  %h1 Ma page
  %ul.user-infos
    %li
      = @user.prenom
      = @user.nom
    %li
      = @user.email
- else
  %h1 Show vue
- unless @succeeded_subscriptions.empty?
  %h2 Liste des objectifs accomplis
  %ul.list-achievements-user
    - @succeeded_subscriptions.each do |subscription|
      %li
        = subscription.id
        = image_tag subscription.achievement.badge.url

- unless @not_succeeded_subscriptions.empty?
  %h2 Liste des objectifs en cours
  - @not_succeeded_subscriptions.each do |subscription|
    %ul.current-list-achievements-user
      %li
        = subscription.id
      %li
        = image_tag subscription.achievement.badge.url
      %li
        = "Nombre de votes : #{subscription.votes.count}"
      - unless subscription.votes.find_by_user_id(current_user.id)
        %li
          = link_to 'Voter', votes_path( { vote: { user_id: current_user.id, subscription_id: subscription.id } } ), method: :create